name: Bot Apply

on:
  workflow_dispatch:
    inputs:
      files_b64:
        description: 'Base64(JSON array): [{ "path": "site/index.html", "b64": "<base64>" }, ...]'
        required: true
        type: string

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode file list
        id: decode
        run: |
          echo "${{ github.event.inputs.files_b64 }}" | base64 -d > .bot_files.json
          node -e "const fs=require('fs'),p=require('path');
          const arr=JSON.parse(fs.readFileSync('.bot_files.json','utf8'));
          for(const f of arr){ fs.mkdirSync(p.dirname(f.path),{recursive:true}); fs.writeFileSync(f.path, Buffer.from(f.b64,'base64')); }
          console.log('Wrote',arr.length,'files');"

      - name: Commit
        run: |
          git config user.name "UTEAM-BOT"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "bot-apply: $GITHUB_RUN_NUMBER" || echo "Nothing to commit"

      - name: Push
        run: git push
